export const projects = [
  {
    name: "Yoom - Zoom Clone",
    link: "https://zoom-clone-five-iota.vercel.app/",
    src: "/zoom-clone.jpg",
    alt: "miniature of app",
    technologies: [
      "Typescript",
      "Next.js",
      "Tailwind CSS",
      "CSS",
      "Shadcn",
      "Clerk",
      "GetStream",
      "ESLint",
      "git",
    ],
  },
  {
    name: "Facebook Clone",
    link: "https://facebook-copy-bice.vercel.app/",
    src: "/facebook-clone.jpg",
    alt: "miniature of app",
    technologies: [
      "Typescript",
      "Next.js",
      "Tailwind CSS",
      "CSS",
      "NextUI",
      "OpenAI",
      "Firebase",
      "Firestore",
      "ESLint",
      "git",
    ],
  },
  {
    name: "Fleet Manager",
    link: "https://fleet-manager-five.vercel.app/",
    src: "/fleet-manager.jpg",
    alt: "miniature of app",
    technologies: ["React", "MaterialUI", "Firebase", "Firestore", "git"],
  },
  {
    name: "Oddaj Rzeczy",
    link: "https://oddaj-rzeczy-five.vercel.app/",
    src: "/oddaj-rzeczy.jpg",
    alt: "miniature of app",
    technologies: ["Next.js", "Tailwind CSS", "Firebase", "Firestore", "git"],
  },
  {
    name: "Best Shop",
    link: "https://best-shop-as.netlify.app/",
    src: "/best-shop.jpg",
    alt: "miniature of app",
    technologies: ["HTML", "CSS", "SCSS", "JavaScript", "git"],
  },
  {
    name: "Car Sharing",
    link: "https://ajek1993.github.io/Car-Sharing/",
    src: "/car-sharing.jpg",
    alt: "miniature of aplication 4",
    technologies: ["HTML", "CSS", "git"],
  },
];
